# Generated by Django 2.0.2 on 2018-02-25 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilingDocumentSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(db_index=True, max_length=1024, null=True)),
                ('sequence', models.IntegerField(db_index=True, default=0)),
                ('file_name', models.CharField(max_length=1024, null=True)),
                ('tag_type', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('start_pos', models.IntegerField(db_index=True)),
                ('end_pos', models.IntegerField(db_index=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormIndex',
            fields=[
                ('edgar_uri', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('index_type', models.CharField(db_index=True, max_length=64)),
                ('size_raw', models.IntegerField()),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('date_published', models.DateField(db_index=True)),
                ('date_downloaded', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FormIndexRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_index=True, max_length=1024)),
                ('s3_path', models.CharField(db_index=True, default=None, max_length=1024, null=True)),
                ('form_type', models.CharField(db_index=True, max_length=64)),
                ('company_name', models.CharField(max_length=1024)),
                ('cik', models.CharField(db_index=True, max_length=32)),
                ('date_filed', models.DateField(db_index=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                (
                'form_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedgar.FormIndex')),
            ],
        ),
        migrations.AddField(
            model_name='filingdocumentsegment',
            name='form_index_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedgar.FormIndexRecord'),
        ),
        migrations.AlterUniqueTogether(
            name='filingdocumentsegment',
            unique_together={('form_index_record', 'sequence')},
        ),
    ]
