# Generated by Django 2.0.2 on 2018-06-24 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cik', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('last_name', models.CharField(db_index=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
                ('sic', models.CharField(db_index=True, max_length=1024, null=True)),
                ('state_location', models.CharField(db_index=True, max_length=32, null=True)),
                ('state_incorporation', models.CharField(db_index=True, max_length=32, null=True)),
                ('business_address', models.CharField(max_length=1024, null=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedgar.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(db_index=True, max_length=64, null=True)),
                ('accession_number', models.CharField(max_length=1024, null=True)),
                ('date_filed', models.DateField(db_index=True, null=True)),
                ('sha1', models.CharField(db_index=True, max_length=1024, null=True)),
                ('s3_path', models.CharField(db_index=True, max_length=1024)),
                ('document_count', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openedgar.Company')),
            ],
        ),
        migrations.CreateModel(
            name='FilingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=1024, null=True)),
                ('sequence', models.IntegerField(db_index=True, default=0)),
                ('file_name', models.CharField(max_length=1024, null=True)),
                ('content_type', models.CharField(max_length=1024, null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('sha1', models.CharField(db_index=True, max_length=1024)),
                ('start_pos', models.IntegerField(db_index=True)),
                ('end_pos', models.IntegerField(db_index=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedgar.Filing')),
            ],
        ),
        migrations.CreateModel(
            name='FilingIndex',
            fields=[
                ('edgar_url', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('date_published', models.DateField(db_index=True, null=True)),
                ('date_downloaded', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('total_record_count', models.IntegerField(default=0)),
                ('bad_record_count', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(db_index=True, max_length=64, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_completed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('filing_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedgar.FilingDocument')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedgar.SearchQuery')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQueryTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=128)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedgar.SearchQuery')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='filingdocumentsegment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='filingdocumentsegment',
            name='form_index_record',
        ),
        migrations.RemoveField(
            model_name='formindexrecord',
            name='form_index',
        ),
        migrations.DeleteModel(
            name='FilingDocumentSegment',
        ),
        migrations.DeleteModel(
            name='FormIndex',
        ),
        migrations.DeleteModel(
            name='FormIndexRecord',
        ),
        migrations.AddField(
            model_name='searchqueryresult',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedgar.SearchQueryTerm'),
        ),
        migrations.AlterUniqueTogether(
            name='searchqueryterm',
            unique_together={('search_query', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='filingdocument',
            unique_together={('filing', 'sequence')},
        ),
    ]
